image: jmgoldacker98/questionnaire-toolset-builder:1.3

stages:
  - build
  - deploy

build:
  type: build
  artifacts:
    paths:
        - Questionnaire_Toolset.zip
  script:
    - cd web-app/
    - mkdir build/
    - cp src/index.html build/
    - cp src/stylesheet.css build/
    - cp src/*.js build/
    - /elm make src/Main.elm --output=build/elm.js
    - cp build/* ../electron-app/questionnaire_gen_win32/resources/app
    - cp build/* ../electron-app/questionnaire_gen_win64/resources/app
    - cd ..
    - zip -r Questionnaire_Toolset.zip electron-app/questionnaire_gen_win32 electron-app/questionnaire_gen_win64

deploy:
  type: deploy
  environment:
    name: staging
  ## only:
    ## - master
  script:
    ## Upload binaries and get url
    - url=$(curl --request POST --header 'PRIVATE-TOKEN:C6mw_oz3AezQRp5Q-ywX' --form 'file=@Questionnaire_Toolset.zip' https://gitlab.informatik.uni-halle.de/api/v4/projects/916/uploads | jq '.url')
    - url=$(echo "$url" | sed -e 's/^"//' -e 's/"$//')
    - url=https://gitlab.informatik.uni-halle.de/projektpraktikum-ss19/fragebogengenerator$url
    ## Set version 
    - MAJOR=0
    - MINOR=8
    - REVISION=$(curl --header "PRIVATE-TOKEN:C6mw_oz3AezQRp5Q-ywX" https://gitlab.informatik.uni-halle.de/api/v4/projects/916/variables | jq '.[0].value|tonumber')
    - VERSION=$MAJOR.$MINOR.$REVISION
    ## Create release
    - TAG=v$VERSION
    - curl --header 'Content-Type:application/json' --header "PRIVATE-TOKEN:C6mw_oz3AezQRp5Q-ywX" --data '{ "tag_name":"'"$TAG"'", "ref":"master", "description":"Release of the questionnaire toolset.", "assets":{ "links":[{ "name":"Binary", "url":"'"$url"'" }] } }' --request POST https://gitlab.informatik.uni-halle.de/api/v4/projects/916/releases
    ## Update patch number
    - REVISION=$((REVISION + 1))
    - curl --request PUT --header "PRIVATE-TOKEN:C6mw_oz3AezQRp5Q-ywX" "https://gitlab.informatik.uni-halle.de/api/v4/projects/916/variables/REVISION" --form "value=$REVISION"