image: jmgoldacker98/questionnaire-toolset-builder:1.5

stages:
  - build
  - deploy

build:
  type: build
  artifacts:
    paths:
        - url.txt
  script:
    ## Build web app and electron app
    - cd web-app/
    - mkdir build/
    - cp src/index.html build/
    - cp src/stylesheet.css build/
    - cp src/*.js build/
    - /elm make src/Main.elm --output=build/elm.js
    - cp build/* ../electron-app/questionnaire_gen_win32/resources/app
    - cp build/* ../electron-app/questionnaire_gen_win64/resources/app
    - cd ..
    ## Build android app
    - cd android-app
    - chmod +x ./gradlew
    - ./gradlew assembleDebug
    - mv app/build/outputs/apk/debug/app-debug.apk app.apk
    - cd ..
    ## Build converter
    - cd converter
    - mvn clean install
    - mv target/*.jar .
    - cd ..
    ## Zip binaries
    - zip -r -D Questionnaire_Toolset.zip electron-app/questionnaire_gen_win32 electron-app/questionnaire_gen_win64 android-app/app.apk converter/*.jar
    ## Upload binaries and get url
    - url=$(curl --request POST --header "PRIVATE-TOKEN:$TOKEN" --form 'file=@Questionnaire_Toolset.zip' https://gitlab.informatik.uni-halle.de/api/v4/projects/916/uploads | jq '.url')
    - url=$(echo "$url" | sed -e 's/^"//' -e 's/"$//')
    - url=https://gitlab.informatik.uni-halle.de/projektpraktikum-ss19/fragebogengenerator$url
    - echo $url > url.txt

deploy:
  type: deploy
  environment:
    name: staging
  ## only:
    ## - master
  script:
    ## Set version 
    - url=$(cat url.txt)
    - MAJOR=0
    - MINOR=8
    - REVISION=$(curl --header "PRIVATE-TOKEN:$TOKEN" https://gitlab.informatik.uni-halle.de/api/v4/projects/916/variables | jq '.[0].value|tonumber')
    - VERSION=$MAJOR.$MINOR.$REVISION
    ## Create release
    - TAG=v$VERSION
    - curl --header 'Content-Type:application/json' --header "PRIVATE-TOKEN:$TOKEN" --data '{ "tag_name":"'"$TAG"'", "ref":"master", "description":"Release of the questionnaire toolset.", "assets":{ "links":[{ "name":"Binary", "url":"'"$url"'" }] } }' --request POST https://gitlab.informatik.uni-halle.de/api/v4/projects/916/releases
    ## Update patch number
    - REVISION=$((REVISION + 1))
    - curl --request PUT --header "PRIVATE-TOKEN:$TOKEN" "https://gitlab.informatik.uni-halle.de/api/v4/projects/916/variables/REVISION" --form "value=$REVISION"