image: jmgoldacker98/questionnaire-toolset-builder:1.3

stages:
  - build
  - deploy

build:
  type: build
  artifacts:
    paths:
        - web-app/build/
  script:
    - cd web-app/
    - mkdir build/
    - cp src/index.html build/
    - cp src/stylesheet.css build/
    - cp src/*.js build/
    - /elm make src/Main.elm --output=build/elm.js

deploy:
  type: deploy
  environment:
    name: staging
  script:
    ## Zip the binaries
    - zip -r Questionnaire_Toolset.zip web-app/build
    ## Upload binaries and get url
    - url=$(curl --request POST --header 'PRIVATE-TOKEN:C6mw_oz3AezQRp5Q-ywX' --form 'file=@Questionnaire_Toolset.zip' https://gitlab.informatik.uni-halle.de/api/v4/projects/916/uploads | jq '.url')
    - url=$(echo "$url" | sed -e 's/^"//' -e 's/"$//')
    - url=https://gitlab.informatik.uni-halle.de/projektpraktikum-ss19/fragebogengenerator$url
    ## Set version 
    - MAJOR=0
    - MINOR=8
    - REVISION=$(curl --header "PRIVATE-TOKEN:C6mw_oz3AezQRp5Q-ywX" https://gitlab.informatik.uni-halle.de/api/v4/projects/916/variables | jq '.[0].value|tonumber')
    - VERSION=$MAJOR.$MINOR.$REVISION
    ## Create tag for release
    - curl --request POST --header "PRIVATE-TOKEN:C6mw_oz3AezQRp5Q-ywX" "https://gitlab.informatik.uni-halle.de/api/v4/projects/916/repository/tags?tag_name=v$VERSION&ref=master"
    ## Create release
    - curl --header 'Content-Type:application/json' --header "PRIVATE-TOKEN:C6mw_oz3AezQRp5Q-ywX" --data '{ "tag_name":"v"$VERSION, "ref":"master", "description":"Test", "assets":{ "links":[{ "name":"Binary", "url":$url }] } }' --request POST https://gitlab.informatik.uni-halle.de/api/v4/projects/916/releases
    ## Update patch number
    - REVISION=$REVISION + 1
    - curl --request PUT --header "PRIVATE-TOKEN:C6mw_oz3AezQRp5Q-ywX" "https://gitlab.informatik.uni-halle.de/api/v4/projects/916/variables/REVISION" --form "value=$REVISION"