image: jmgoldacker98/questionnaire-toolset-builder

stages:
  - build
  - deploy

build:
  type: build
  script:
    - cd web-app/
    - mkdir build/
    - cp src/index.html build/
    - cp src/stylesheet.css build/
    - cp src/*.js build/
    - /elm make src/Main.elm --output=build/elm.js

deploy:
  type: deploy
  environment:
    name: staging
  script:
    - echo 'foo'