image: jmgoldacker98/questionnaire-toolset-builder:1.1

stages:
  - build
  - deploy

build:
  type: build
  artifacts:
    paths:
        - web-app/build/
  script:
    - cd web-app/
    - mkdir build/
    - cp src/index.html build/
    - cp src/stylesheet.css build/
    - cp src/*.js build/
    - /elm make src/Main.elm --output=build/elm.js

deploy:
  type: deploy
  environment:
    name: staging
  script:
    - zip -r Questionnaire_Toolset.zip web-app/build
    - curl --request POST --header 'PRIVATE-TOKEN:C6mw_oz3AezQRp5Q-ywX' --form 'file=@Questionnaire_Toolset.zip' https://gitlab.informatik.uni-halle.de/api/v4/projects/916/uploads
    